def menu():
    menus = [
            {'id' : '1',
            'name' : 'Lele Manis Madu',
            'price': '16000'},
            {'id' : '2',
            'name' : 'Lele Goreng',
            'price': '10000'},
            {'id' : '3',
            'name' : 'Lele Rebus',
            'price': '8000'},
            {'id' : '4',
            'name' : 'Lele Teriyaki',
            'price': '14000'},
            {'id' : '5',
            'name' : 'Bebek Tiramisu',
            'price': '21000'},
            {'id' : '6',
            'name' : 'Bebek Bakar Madu',
            'price': '16000'},
            {'id' : '7',
            'name' : 'Bebek Goreng',
            'price': '12000'},
            {'id' : '8',
            'name' : 'Bebek Sambel Madura',
            'price': '14000'},
            {'id' : '9',
            'name' : 'Iga Bakar Keju Lebay',
            'price': '32000'},
            {'id' : '10',
            'name' : 'Iga Asam Manis',
            'price': '24000'},
            {'id' : '11',
            'name' : 'Sop Iga Aja',
            'price': '18000'},
            {'id' : '12',
            'name' : 'Es Teh Manis',
            'price': '3000'},
            {'id' : '13',
            'name' : 'Es Teh Manis Anget',
            'price': '4000'},
            {'id' : '14',
            'name' : 'Es Jeruk Botol',
            'price': '8000'},
            {'id' : '15',
            'name' : 'Air Tembus Pandang',
            'price': '5000'},
            {'id' : '16',
            'name' : 'Jamur Disko',
            'price': '8000'},
            {'id' : '17',
            'name' : 'Terong Cepmek',
            'price': '8000'},
            {'id' : '18',
            'name' : 'Tahu Brontak',
            'price': '5000'},
            {'id' : '19',
            'name' : 'Tembe',
            'price': '5000'}
    ]
    return menus

def crew():
    crews = [
            {'id' : '1',
            'nim' : '19221493',
            'name': 'Muhammad Naufal Ihza Fadhilah'},
            {'id' : '2',
            'nim' : '19220693',
            'name': 'Aziz Ahadrianto'},
            {'id' : '3',
            'nim' : '19220768',
            'name': 'Alfa Rizy'},
            {'id' : '4',
            'nim' : '19220682',
            'name': 'M Bevi Arianda Anwar'},
            {'id' : '5',
            'nim' : '19220458',
            'name': 'M Zulfikar Noor'},
            {'id' : '6',
            'nim' : '19220788',
            'name': 'Dede saefulloh'},
    ]
    return crews

        